# Generated by Django 4.2.6 on 2023-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
