# Generated by Django 4.2.6 on 2023-10-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0003_pokemonentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="title",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="pokemon_entities.pokemon",
                verbose_name="Pokemon name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title",
            field=models.CharField(max_length=128, verbose_name="Pokemon name"),
        ),
    ]
