# Generated by Django 4.2.6 on 2023-10-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0005_pokemonentity_appeared_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemonentity",
            name="defence",
            field=models.IntegerField(default=5, max_length=12),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(default=5, max_length=12),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(default=5, max_length=12),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(default=5, max_length=12),
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="strength",
            field=models.IntegerField(default=5, max_length=12),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="latitude",
            field=models.FloatField(verbose_name="Широта точки"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="longitude",
            field=models.FloatField(verbose_name="Долгота точки"),
        ),
    ]
