# Generated by Django 4.2.6 on 2023-10-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pokemon_entities",
            "0006_pokemonentity_defence_pokemonentity_health_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemonentity",
            name="defence",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="health",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="stamina",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="strength",
            field=models.IntegerField(default=5),
        ),
    ]
