# Generated by Django 4.2.6 on 2023-10-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0007_alter_pokemonentity_defence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="description",
            field=models.TextField(
                blank=True, max_length=256, verbose_name="Pokemon description"
            ),
        ),
    ]
