# Generated by Django 4.2.6 on 2023-10-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0009_alter_pokemon_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                default=6, max_length=128, verbose_name="Pokemon English name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                default=15, max_length=128, verbose_name="Pokemon Japan name"
            ),
            preserve_default=False,
        ),
    ]
