# Generated by Django 4.2.6 on 2023-10-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0011_pokemon_previous_evolution_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemonentity",
            name="title",
        ),
        migrations.AddField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pokemon_entitys",
                to="pokemon_entities.pokemon",
                verbose_name="Pokemon name",
            ),
            preserve_default=False,
        ),
    ]
