# Generated by Django 4.2.6 on 2023-10-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pokemon_entities", "0012_remove_pokemonentity_title_pokemonentity_pokemon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="description",
            field=models.TextField(verbose_name="Pokemon description"),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Pokemon English name"
            ),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="title_jp",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Pokemon Japan name"
            ),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="appeared_at",
            field=models.DateTimeField(blank=True, verbose_name="Появится в:"),
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="disappeared_at",
            field=models.DateTimeField(
                blank=True, default=1, verbose_name="Исчезнет в:"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pokemonentity",
            name="pokemon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entities",
                to="pokemon_entities.pokemon",
                verbose_name="Pokemon name",
            ),
        ),
    ]
